### ISSUE TITLE
Config error

### ISSUE THREAD

**Issue by Dimatert9** [ItsMennyo/Flex-AntiCheat#7]
**Which AntiCheat do you use? AAC, AACAdditionPro or AntiAura?**

**AntiCheat**: ~~Latest aac and aac additional pro~~

**What's the problem? Bypass, False Positive, Bug or Help?**

**Problem**:  ~~Bypass/Bug/Help~~ Bug

---

**What version does your server use?**

**Server Version**: ~~1.12.2~~ 

**Which Minecraft client did you use?**

**Minecraft Client**:  ~~1.8.9~~

---

**Which BUILD of Flex do you use?**

**Flex BUILD**: ~~Latest public for aac and~~ aacap without changes

---

**What is the AntiCheat version itself?**

**AntiCheat Version**: ~~3.3.11-b1 and 3.10.1~~

---

**Do you have any proof?**

**Video or Photo**:  ~~https://youtu.be/f-hZvJO2lzY~~

---

**Try to explain your problem...**

**Description**: ~~scaffold and tower works without any problem.~~
Config has error on 590 line

**Comment by Dimatert9** [comment]
hmm. i check logs and detect that a config has a erorr
https://github.com/ItsMennyo/Flex-AntiCheat/blob/master/AACAdditionPro/LATEST%20PUBLIC%20BUILD.yml#L590

```
[20:08:09] [Server thread/INFO]: [AACAdditionPro] Enabling AACAdditionPro v3.10.1
[20:08:10] [Server thread/ERROR]: Cannot load plugins/AACAdditionPro/config.yml
org.bukkit.configuration.InvalidConfigurationException: while parsing a block collection
 in 'string', line 590, column 7:
          - "aackick {player} LabyMod
          ^
expected <block end>, but found Scalar
 in 'string', line 598, column 10:
          - "aackick {player} LiteLoader"
             ^

	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55) ~[Spigot.jar:git-Spigot-4bd94dc-bacaf92]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:162) ~[Spigot.jar:git-Spigot-4bd94dc-bacaf92]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:130) ~[Spigot.jar:git-Spigot-4bd94dc-bacaf92]
	at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:178) [Spigot.jar:git-Spigot-4bd94dc-bacaf92]
	at de.photon.AACAdditionPro.AACAdditionPro.getConfig(AACAdditionPro.java:61) [AACAdditionPro-3.10.1.jar:?]
	at de.photon.AACAdditionPro.aZ.<clinit>(aZ.java:1) [AACAdditionPro-3.10.1.jar:?]
	at de.photon.AACAdditionPro.AACAdditionPro.onEnable(AACAdditionPro.java:113) [AACAdditionPro-3.10.1.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) [Spigot.jar:git-Spigot-4bd94dc-bacaf92]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [Spigot.jar:git-Spigot-4bd94dc-bacaf92]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [Spigot.jar:git-Spigot-4bd94dc-bacaf92]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [Spigot.jar:git-Spigot-4bd94dc-bacaf92]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [Spigot.jar:git-Spigot-4bd94dc-bacaf92]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [Spigot.jar:git-Spigot-4bd94dc-bacaf92]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [Spigot.jar:git-Spigot-4bd94dc-bacaf92]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [Spigot.jar:git-Spigot-4bd94dc-bacaf92]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [Spigot.jar:git-Spigot-4bd94dc-bacaf92]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [Spigot.jar:git-Spigot-4bd94dc-bacaf92]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: org.yaml.snakeyaml.parser.ParserException: while parsing a block collection
 in 'string', line 590, column 7:
          - "aackick {player} LabyMod
          ^
expected <block end>, but found Scalar
 in 'string', line 598, column 10:
          - "aackick {player} LiteLoader"
             ^

	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockSequenceEntry.produce(ParserImpl.java:515) ~[Spigot.jar:git-Spigot-4bd94dc-bacaf92]
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:157) ~[Spigot.jar:git-Spigot-4bd94dc-bacaf92]
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:147) ~[Spigot.jar:git-Spigot-4bd94dc-bacaf92]
	at org.yaml.snakeyaml.composer.Composer.composeSequenceNode(Composer.java:200) ~[Spigot.jar:git-Spigot-4bd94dc-bacaf92]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:152) ~[Spigot.jar:git-Spigot-4bd94dc-bacaf92]
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:249) ~[Spigot.jar:git-Spigot-4bd94dc-bacaf92]
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:240) ~[Spigot.jar:git-Spigot-4bd94dc-bacaf92]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:228) ~[Spigot.jar:git-Spigot-4bd94dc-bacaf92]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:154) ~[Spigot.jar:git-Spigot-4bd94dc-bacaf92]
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:249) ~[Spigot.jar:git-Spigot-4bd94dc-bacaf92]
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:240) ~[Spigot.jar:git-Spigot-4bd94dc-bacaf92]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:228) ~[Spigot.jar:git-Spigot-4bd94dc-bacaf92]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:154) ~[Spigot.jar:git-Spigot-4bd94dc-bacaf92]
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:249) ~[Spigot.jar:git-Spigot-4bd94dc-bacaf92]
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:240) ~[Spigot.jar:git-Spigot-4bd94dc-bacaf92]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:228) ~[Spigot.jar:git-Spigot-4bd94dc-bacaf92]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:154) ~[Spigot.jar:git-Spigot-4bd94dc-bacaf92]
	at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122) ~[Spigot.jar:git-Spigot-4bd94dc-bacaf92]
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105) ~[Spigot.jar:git-Spigot-4bd94dc-bacaf92]
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:140) ~[Spigot.jar:git-Spigot-4bd94dc-bacaf92]
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:524) ~[Spigot.jar:git-Spigot-4bd94dc-bacaf92]
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:437) ~[Spigot.jar:git-Spigot-4bd94dc-bacaf92]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:53) ~[Spigot.jar:git-Spigot-4bd94dc-bacaf92]
	... 17 more
[20:08:10] [Server thread/INFO]: [AACAdditionPro] Enabling plugin...
[20:08:10] [Server thread/INFO]: [AACAdditionPro] Heuristic-Addition was chosen not to be enabled.
[20:08:10] [Server thread/INFO]: [AACAdditionPro] LogBot was chosen not to be enabled.
[20:08:10] [Server thread/INFO]: [AACAdditionPro] ClientControl-BetterSprinting was chosen not to be enabled.
[20:08:10] [Server thread/INFO]: [AACAdditionPro] ClientControl.DamageIndicator was chosen not to be enabled.
[20:08:10] [Server thread/INFO]: [AACAdditionPro] ClientControl-5zig was chosen not to be enabled.
[20:08:10] [Server thread/INFO]: [AACAdditionPro] ClientControl-Forge was chosen not to be enabled.
[20:08:10] [Server thread/INFO]: [AACAdditionPro] ClientControl-LiteLoader was chosen not to be enabled.
[20:08:10] [Server thread/INFO]: [AACAdditionPro] ClientControl-OldLabyMod was chosen not to be enabled.
[20:08:10] [Server thread/INFO]: [AACAdditionPro] ClientControl-BetterSprinting was chosen not to be enabled.
[20:08:10] [Server thread/INFO]: [AACAdditionPro] ClientControl-Schematica was chosen not to be enabled.
[20:08:10] [Server thread/INFO]: [AACAdditionPro] ClientControl-Vape was chosen not to be enabled.
[20:08:10] [Server thread/INFO]: [AACAdditionPro] ClientControl-WorldDownloader was chosen not to be enabled.
[20:08:10] [Server thread/ERROR]: [AACAdditionPro] Loading failed:
[20:08:10] [Server thread/WARN]: java.lang.NullPointerException: Severe loading error: Config-Section is null when loading: AutoFish.thresholds
[20:08:10] [Server thread/WARN]: 	at java.util.Objects.requireNonNull(Objects.java:228)
[20:08:10] [Server thread/WARN]: 	at de.photon.AACAdditionPro.bq.b(bq.java:5)
[20:08:10] [Server thread/WARN]: 	at de.photon.AACAdditionPro.bq.c(bq.java:15)
[20:08:10] [Server thread/WARN]: 	at de.photon.AACAdditionPro.b_.<init>(b_.java:47)
[20:08:10] [Server thread/WARN]: 	at de.photon.AACAdditionPro.D.<init>(D.java:41)
[20:08:10] [Server thread/WARN]: 	at de.photon.AACAdditionPro.AACAdditionPro.onEnable(AACAdditionPro.java:22)
[20:08:10] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[20:08:10] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[20:08:10] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
[20:08:10] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381)
[20:08:10] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330)
[20:08:10] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422)
[20:08:10] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383)
[20:08:10] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338)
[20:08:10] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272)
[20:08:10] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545)
[20:08:10] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by ItsMennyo** [comment]
Fixed: https://github.com/ItsMennyo/Flex-AntiCheat/commit/b71f52be782538744378b56339720202558ab691#diff-71bc84f87017eee5975a3a2f72da2545
Recopy the config or look at the link what need to be changed.

Tnxx for reporting!
